name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.x

      - name: Run a multi-line script
        run: |
          cd InterviewQuestion
          dotnet build
          dotnet run InterviewQuestion.dll
